CREATE TABLE "Animal" (
	`IdAnimal`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	        TEXT NOT NULL,
	`IdHabitat`	INTEGER NOT NULL,
	`IdSpecies`	INTEGER NOT NULL
);

CREATE TABLE "Habitat" (
	`IdHabitat`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	        TEXT NOT NULL,
	`IdType`	INTEGER NOT NULL
);

CREATE TABLE "HabitatType" (
	`IdType`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	        TEXT NOT NULL
);

CREATE TABLE `Species` (
	`IdSpecies`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ScientificName`	TEXT NOT NULL,
	`CommonName`	TEXT,
	`WikiLink`	TEXT
);

